services:
  - type: web
    name: treatz-tx-api
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    rootDir: apps/tx-api
    envVars:
      - key: RPC
        value: https://api.devnet.solana.com
      - key: PROGRAM_ID
        value: REPLACE
      - key: GLOBAL
        value: REPLACE
      - key: TREATZ_MINT
        value: REPLACE
      - key: TREASURY_TA
        value: REPLACE
      - key: WEB_URL
        value: https://your-web.example.com

  - type: worker
    name: treatz-telegram-bot
    env: python
    rootDir: apps/telegram-bot
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: REPLACE
      - key: TXAPI
        fromService:
          name: treatz-tx-api
          type: web
          property: url

  - type: worker
    name: treatz-discord-bot
    env: python
    rootDir: apps/discord-bot
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DISCORD_TOKEN
        value: REPLACE
      - key: TXAPI
        fromService:
          name: treatz-tx-api
          type: web
          property: url
