[features]
seeds = true

[programs.devnet]
treatz_flip = "11111111111111111111111111111111" # replace after first deploy

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
build = "anchor build"
deploy = "anchor deploy"
